apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-c-60-
  namespace: argo-workflows
spec:
  serviceAccountName: argo-workflows-executor
  workflowTemplateRef:
    name: stats-s2-geomad-annual
  arguments:
    parameters:
      - name: output-path
        value: "gm_s2"
      - name: db-path
        value: /data/public/geomad_task/2025/s2_l2a_2025--P1Y.db
