# Main configuration for odc-stats processing
product:
  name: geomad_s2_annual
  short_name: geomad_s2_annual
  version: 1.0.0
  product_family: geomedian
  region_code_format: "x{x:03d}y{y:03d}"
  collections_site: "collections.staging.piksel.big.go.id"
  producer: "big.go.id"
  naming_conventions_values: "de-indonesia-"
  explorer_path: "https://explorer.staging.piksel.big.go.id/"
  
output:
  write_stac: true
  write_data: true
  location_prefix: ""

write_metadata: false

# COG output options
cog_opts:
  zlevel: 9
  overrides:
    rgba:
      compress: JPEG
      jpeg_quality: 90

max_processing_time: 3600
job_queue_max_lease: 300
renew_safety_margin: 60
future_poll_interval: 2
s3_acl: public-read
s3_public: true