# Plugin-specific configuration for gm-s2
resampling: nearest

# Cloud filtering configuration
cloud_filters:
  'cloud medium probability':
    - [opening, 2]
    - [dilation, 5]
  'cloud high probability':
    - [opening, 2] 
    - [dilation, 5]
  'thin cirrus':
    - [dilation, 5]

# Band selection
bands:
  - blue
  - red
  - green
  - rededge1
  - rededge2
  - rededge3
  - nir
  - nir08
  - swir16
  - swir22

rgb_bands:
  - red
  - green
  - blue

# Processing chunks
work_chunks: [600, 600]

